### ISSUE TITLE
Calling setIdentity multiple times with same identity problem

### ISSUE THREAD

**Issue by sweinertjr** [BranchMetrics/Branch-PhoneGap-Cordova-SDK#4]
When we build a short URL we are trying to set the identity of the user so it integrates with the Branch Metrics dashboard, but upon calling it a second time with the latest code, I receive no response from the method, which stalls our app.

I noticed in your latest version you changed Branch.m the `- (void)setIdentity:(NSString *)userId ` method to not only check for a missing `userId` but also check if the `userId` has not changed. It is now:

`if (!userId || [[BNCPreferenceHelper getUserIdentity] isEqualToString:userId])`

This makes sense, however, upon it finding that it is equal, it simply returns and the callback doesn't seem to fire back to our app. 

This looks intentional, so I am wondering whether I am using the setIdentity method incorrectly. Should I only be calling it once? 

Thanks for your help!

**Comment by aaustin** [comment]
@sweinertjr Thanks for the note. 

We intended setIdentity to only be called once, when you've first determine the user id for a particular person in your app. However, some people wanted to call set identity with a randomly generated string until a user logged in, and then call it with a real user id. In order to only call it once, they'd have to store that state themselves. To make it easier from an implementation perspective, we added a safeguard to cut down on requests to our server so that it's fine to call it multiple times!

**Comment by sweinertjr** [comment]
@aaustin Okay good to know. Obviously it wouldn't make sense to send a request to the server, but do you think it would be better to still return a callback even if it's already set? Otherwise it's kind of hard to know what `setIdentity` did when it doesn't even respond. Thoughts?

**Comment by aaustin** [comment]
Ohh I see your point. That's completely fair.

Let me add that in tonight. I'll send you a note when it's live

**Comment by sweinertjr** [comment]
@aaustin I'm super impressed with how well you maintain this code. Thanks.

**Comment by aaustin** [comment]
I'm just a guy that loves Branch

**Comment by aaustin** [comment]
@sweinertjr all updated up. It should callback 100% of the time now. This was due to an oversimplification of my wrapper around the native SDK, which has two methods public, as you noticed.

Thanks for the heads up!

**Comment by sweinertjr** [comment]
@aaustin @sean-hill great! We will give this new version a shot.
